site_name: Wikistats template

use_directory_urls: false

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
  - Home: index.md
  - Courses:
    - Course 1: course1.md
    - Course 2: 
      - Course 2-a: course2a.md
      - Course 2-b: course2b.md
      
  - Schedule: schedule.md
  - Evaluation: evaluation.md
  - Github repository: https://github.com/wikistat/
#theme: slate
theme:
  name: 'flatly'
  logo: img/logo-insa.jpg
  favicon: img/favicon.ico


