site_name: Machine Learning course

use_directory_urls: false

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
  - Home: index.md
  - Lectures: lectures.md
  - Schedule: schedule.md
  - Evaluation: evaluation.md
  - Github repository: https://github.com/wikistat/Apprentissage
#theme: slate
theme:
  name: 'flatly'
  logo: img/logo-insa.jpg
  favicon: img/favicon.ico


